name: example

on: 
  push:

jobs:


 

  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        java : ['8','11','17']
        os : ['macos-latest','windows-latest','ubuntu-latest']
    name : Java ${{matrix.java}} ejemplo
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{matrix.java}}


